decentraland/kernel

- kernel/packages/shared/comms/v2/LighthouseWorldInstanceConnection.ts
Fixes an issue that would make the "existing session" message to be shown as a generic error
> fix: Correctly sending the status handler to the LayerBasedPeer

- packages/voice-chat-codec/VoiceCommunicator.ts
Add a check for aContext.audioWorklet.
For some reason, sometimes AudioContext initializes without audioWorklet defined in it.
> fix: avoid call audioWorklet.addModule if it's undefined

- packages/config/index.ts
- packages/voice-chat-codec/audioWorkletProcessors.ts
This PR fixes a corner case that would make Voice Chat completely fail on firefox sometimes.
This doesn't completely fix Voice Chat since there is an issue that I'm still investigating with web workers communication (and that seems to affect more things than just Voice Chat), but should improve the situation.
Also, we should get better connection results with less stun servers.
> fix: Voice chat sometimes fails in Firefox

- packages/shared/rolloutVersions.ts
- packages/shared/types.ts
- packages/unity-interface/kernelConfigForRenderer.ts
Adds kernel and renderer versions to kernelConfigForRenderer
Required for decentraland/unity-renderer#1178 to autocomplete issue form with required data
Follow https://github.com/decentraland/unity-renderer/pull/1187 Instructions
> feat: Add kernel and renderer versions to kernelConfigForRenderer data

- packages/config/index.ts
- packages/decentraland-loader/lifecycle/manager.ts
re-enable test-scenes for debugging.
using url param `ENABLE_TEST_SCENES`
also added url param `DISABLE_EMPTY_SCENES` to avoid loading empty-parcels (mostly for debugging porpoises)
> fix: test-scenes not loading

- static/export.html
Add a default position at open the html.
It's neccesary to replace from setupExport of decentraland-ecs to real scene.json base position.
If the string `{{ scene.scene.base }}` isn't replaced to the x,y position, the kernel assign automatically 0,0 as now is doing.
https://github.com/decentraland/sdk/issues/84
https://github.com/decentraland/js-sdk-toolchain/pull/28
> feat: add a default start position at open export.html file

- packages/entryPoints/index.ts
- packages/shared/meta/types.ts
- packages/shared/types.ts
- packages/unity-interface/kernelConfigForRenderer.ts
It adds the new feature flag `explorev2` that will be used by `unity-renderer` to enable/disable the new feature **[ExploreV2](https://www.notion.so/decentraland/PRD-Explore-V2-ab98e922c196488fb217596c888ce3d6)** (currently in development) and replace the old "**Explore & Play**" feature.
> feat: Add feature flag for ExploreV2

- packages/shared/comms/index.ts
We are reporting an error twice, and the second time it overrides the previous one, with something that's then reported incorrectly.
The error report that we are removing in this PR is then handled by this piece of code: https://github.com/decentraland/kernel/blob/5554c32bde2b54a0e966d30b98c3a1abc9282ce2/packages/shared/comms/index.ts#L1059
This will improve comms errors reporting, in conjunction with this other PR in website: https://github.com/decentraland/explorer-website/pull/76
> chore: Fixing double error handling so we can better report comms errors

- packages/entryPoints/index.ts
The feature flag should be sent before the asset bundle message since there is a debug system that is needed in order to receive the message to deactivate the assets bundles
> fix: change feature flag message order

- packages/shared/comms/index.ts
- packages/shared/comms/interface/index.ts
- packages/shared/comms/interface/types.ts
- packages/shared/comms/peers.ts
- packages/shared/comms/v2/LighthouseWorldInstanceConnection.ts
Should solve #78.
We have seen that the issue manifests itself when the userId in comms context is not initialized correctly. There is no clear scenario in which this would happen. This is likely a race condition.
With this PR, we make userId in UserInformation not nullable. This should ensure that the condition that makes other people don't see you doesn't happen.
This is the safest solution for the time being. Something that we can ship in short term.
In the future, we should refactor comms in kernel. Reduce redundant information and review the flow of control and information. But that is quite risky to do short term, without a plan.
> fix: userId in comms context should be not nullable

- packages/shared/profiles/sagas.ts
Force to request the profile to peers if you are in preview mode.
If you use preview wearables that aren't deploy in any catalyst, kernel ignores.
This is the web3 profile wearing a preview wearable:
If you are next to the web3 profile you see this:
With the fix:
> fix: web3 wearables in preview mode

- packages/shared/catalogs/sagas.ts
When opening the client with `WITH_COLLECTIONS` query param, if the user doesn't have a profile yet, the wearables request will wait forever.
When that happens the UX is as follows:
1. When entering as an incognito guest the backpack is the first thing you see to create the character
2. The backpack appears totally empty (no base wearables either)
3. After several wearables requests retries from the client (45 secs) the explorer crashes
Issue solved by this PR: https://github.com/decentraland/unity-renderer/issues/1547
Removed unneeded yield that in some occasions breaks the base wearables fetch and thus the client explodes
**Production (bugged)**
Enter this URL **in incognito + guest mode**: https://play.decentraland.zone/?&NETWORK=ropsten&WITH_COLLECTIONS=3062136a-065d-4d94-b28c-f57d6ef0 …
> fix: WITH_COLLECTIONS query param base wearables fetch

- packages/shared/apis/EnvironmentAPI.ts
*deprecated `layer` from `EnvironmentRealm`:
*`layer` is now set with the `island` id
+added `room` field that is set with the `island` id
> fix: deprecate realm's layer from EnvironmentAPI

- packages/shared/apis/SceneStateStorageController/BuilderServerAPIManager.ts
This PR makes BIW able to recover the manifest by coords
When the sign of the headers changed in the builder API, we changed the normal manifest but we didn't change the manifest by coords, this PR changes it now
> fix: manifest from coords load

- packages/unity-interface/loader.ts
fix: remove `?cors` from request to work directly with a static file server like S3
> fix: remove `?cors` from request

- packages/shared/world/parcelSceneManager.ts
- packages/unity-interface/BrowserInterface.ts
Add typings to the events that we send to the scene.
...
To avoid typos or sending invalid payloads.
...
> add allSceneEvents typings

- packages/entryPoints/index.ts
- packages/shared/types.ts
It is the kernel side of https://github.com/decentraland/unity-renderer/issues/1509.
Deprecates the `EXPLORE_HUD` feature.
The `EXPLORE_HUD` feature is not longer needed because it has been replaced by the new `ExploreV2` one.
> feat: [Explore V2] Remove the old Explore feature (Kernel side)

- packages/shared/apis/Permissions.ts
Add a vlidation for land
Portable experience doesn't land attribute.
> fix: hasPermissions function when it's a portable experience.

- packages/shared/dao/index.ts
This pr prevents selecting a catalyst that has a max concurrent users lower or equal to the user count
When a catalyst is not able to accept new connections and an algorithm still picks it, the user experiences an error that's not solvable without refreshing, and in some cases, kernel was still selecting the same realm (for example when the algorithm is 100% load balancing)
> Add filter to prevent selecting a catalyst without capacity

- packages/shared/dao/index.ts
- packages/shared/dao/sagas.ts
- packages/shared/dao/utils/ping.ts
- packages/shared/profiles/sagas.ts
- test/dao/fetchCatalystStatuses.test.ts
- test/dao/index.ts
- test/dao/pick-realm-algorithm/index.ts
- test/index.ts
This pr prevents selecting a catalyst that has a max concurrent users lower or equal to the user count
Removes the zip which depended on the size of both arrays, now it's one map that takes care of building the correct information before filtering
When a catalyst is not able to accept new connections and an algorithm still picks it, the user experiences an error that's not solvable without refreshing, and in some cases, kernel was still selecting the same realm (for example when the algorithm is 100% load balancing)
> Add filter by capacity to catalysts

- packages/shared/apis/RestrictedActions.ts
Change `newPosition` to `position`. NewPosition is the function argument, and position is the finally calculated position.
Fix https://github.com/decentraland/sdk/issues/162
> fix: report a wrong position after movePlayerTo is called.

- packages/shared/world/SceneSystemWorker.ts
- packages/shared/world/positionThings.ts
- packages/unity-interface/BrowserInterface.ts
Decoupled the rotation used for comms and the rotation that is reported to the sdk.
Since: 
*comms needs avatar rotation
*sdk needs camera rotation
> fix: camara rotation reported by renderer

- packages/config/index.ts
- packages/entryPoints/index.ts
- packages/shared/index.ts
- packages/shared/logger/index.ts
- packages/shared/logger/wrap.ts
- packages/unity-interface/UnityParcelScene.ts
- packages/unity-interface/UnityScene.ts
- packages/unity-interface/trace.ts
- test/index.ts
- test/shared/index.ts
- test/shared/logger.spec.ts
Add a string prefix to the logs so we can identify if the logs comes from kernel or another library.
This way we can use the DEBUG_PREFIX url param to filter the logs that we want.
i.e. https://play.decentraland.zone/?kernel-branch=add/wrap-console-log&DEBUG_PREFIX=kernel: will log only the logs that starts with `kernel:`
By default we log everything, so this should not change anything if we dont use the query param.
...
Clean the noise in the console so the user can see only the logs that he wants. i.e. scene logs
...
> add console wrapper

- packages/shared/apis/EthereumController.ts
- packages/shared/ethereum/EthereumService.ts
The pop up of the transaction is been sent even if not needed.
We must add a list of the methods that need user validation to fix it properly.
> feat: only show request web3 api use on require sign

- packages/scene-system/sdk/Fetch.ts
- packages/scene-system/sdk/SceneRuntime.ts
- packages/scene-system/sdk/WebSocket.ts
- test/scene-system/sdk/fetchWrapper.spec.ts
Fix throw in synchronous execution and unifies RequestInit with Opts
...
After merge, update kernel version in https://github.com/decentraland/js-sdk-toolchain/pull/121
> chore: fix exceptions in fetch and use single options object

- packages/shared/friends/sagas.ts
Removes friends initialization error notification
To improve user experience since its failing all the time
> fix: removed friends initialization error notification

- packages/shared/social/avatarTracker.ts
- packages/shared/types.ts
We are removing a property that is not used from the AvatarReporter
Since this property is not used we can safely remove it so the renderer can just delete that property safely. This way we don't need to create another message to support backward compatibility when there is no need for it
> feat: remove entityId from AvatarReporter

- packages/shared/meta/selectors.ts
- test/unit/meta.test.tsx
Fix https://github.com/decentraland/unity-renderer/issues/2171
We're using from the Launcher the URLParams to create the URL to add parameters like:
```
DISABLE_ASSET_BUNDLES
DISABLE_WEARABLES_ASSET_BUNDLES
```
And the output URL using URLParams is:
```
&DISABLE_ASSET_BUNDLES=&DISABLE_WEARABLES_ASSET_BUNDLES=
```
This is totally valid based on http://www.faqs.org/rfcs/rfc2396.html (thanks @leanmendoza)
But the kernel is ignoring it due to incorrect parsing.
> fix: the parsing to disable and enable a feature from the url params

- package-lock.json
- package.json
- packages/shared/catalogs/sagas.ts
- packages/shared/catalogs/types.ts
- packages/unity-interface/BrowserInterface.ts
Adds third party wearables support by extending `WearablesRequest` and using `catalyst-client:fetchOwnedThirdPartyWearables` method.
In order to complete the feature in the Explorer ([PR](https://github.com/decentraland/unity-renderer/pull/1814)), this change is required to avoid explicit HTTP calls to the catalyst and keep using the same flow.
Resolves #257
> feat: add third party ID to WearablesRequest

- packages/ui/avatar/avatarSystem.ts
when avatar was set as not visible or removed and re-added to avoid renderer interpolation
it was also being removed from `avatarMap`
in a race condition `ensureAvatar` could create a new avatar entity even if an entity for that user already exists
for example
```
setPose(pose: Pose): void {
const [x, y, z, Qx, Qy, Qz, Qw, immediate] = pose
const shouldReAddEntity = immediate && this.visible
if (shouldReAddEntity) {
this.remove()  //////////////////////////////----> avatar was being removed from engine and avatarMap
}
this.transform.position.set(x, y, z)
this.transform.rotation.set(Qx, Qy, Qz, Qw)
if (shouldReAddEntity) {
engine.addEntity(this)  //////////////////////////////----> avatar was being re-added to the engine but not to avatarMap
}
}
```
> fix: duplicated avatar for a same user

- packages/shared/world/positionThings.ts
Explorer never finish loading when teleporting to a scene with a wrong format for it spawnpoints.
We can see it happening here: https://play.decentraland.org/?position=-143,-125
> fix: scene loading when wrong format for spawnpoints

- packages/config/index.ts
- packages/shared/catalogs/sagas.ts
This PR adds a method and a new query string to load a set of items from the builder server by id.
We need a way to load sets of items into the world so curators and creators can view small sets of items. This feature is intended to be used with third party collection that contain thousands of items and can't be loaded as collections without pagination.
> feat: Make kernel capable of loading single items from the builder server

- packages/shared/meta/sagas.ts
- packages/shared/meta/selectors.ts
This PR works along with [the global config PR](https://dcl.tools/ops/global-config/-/merge_requests/4/diffs).
Changes Ropsten/dev Synapse URL from `synapse.decentraland.io` to the new one `synapse.decentraland.zone`
The domain was changed for this environment.
> chore: changing Synapse URL for Ropsten/dev

- packages/unity-interface/portableExperiencesUtils.ts
This only brings back the `await sleep` set between the destruction and creation of Portable Experiences coded in:
https://github.com/decentraland/kernel/blob/039d162fdfd587106ab86c4018997cb2498d061f/packages/unity-interface/dcl.ts#L214
The `spawnPx..` right now is ignored if it's called immediately after its destruction.
> fix: hot-reload in smart-wearables

- packages/shared/catalogs/sagas.ts
This PR implements a missing feature that allows the `WITH_ITEMS` property to support item URNs.
**Disclaimer**
A URL has a maximum length of 2048 characters, assuming URNs like `urn:decentraland:mumbai:collections-v2:0x3418e24d99b44e051932e40c98a461f2586be3d7:0` where its length is around 80 characters, only 25 URNs could be asked for and, taking into consideration that the URL usually has other query parameters defined, it will be able to query less than that. The catalyst client has a mechanism to split queries that have long query parameters so these 25 URNs won't break any requests to the Catalyst.
We want to be able to load published items into the world.
> fix: Allow URNs as item ids in the see in world feature

- packages/shared/analytics/hook-observable.ts
- packages/shared/analytics/types.ts
- packages/shared/chat/sagas.ts
- packages/shared/comms/interface/types.ts
- packages/shared/friends/sagas.ts
This reverts commit 96bd2273312aec679adab9838611725ceefe9cfe.
We are reintroducing the chat metrics in kernel in order to have a control to compare with the new ones in renderer.
...
> Revert "Remove chat and friends metrics (#296)"

- docs/tracing.md
Updated tracing document as requested by @menduz to include the `endTrace()` command
> Docs: Updated tracing document

- .github/workflows/set-rollouts.yml
- packages/shared/apis/client/RestrictedActions.ts
Also set .org rollout to 100 (chore)
...
Fix the condition the cameraTarget is sent as null. Before the usage of @dcl/rpc this was working because the field wired as is and the remote procedure received the `null`, so the ifs were working fine. Now the field is serialized and the fields have to be able to be serialized, or if it's not going to wire, be undefined.
> fix: null camera target set as undefined

- packages/renderer-protocol/transports/webTransport.ts
Copy the received data and work with it.
Only it happens in chrome.
While the promises are resolving, the Uint8Array reference linked to the WebAssembly heap is missed.
> fix: (rpc-web-transport) missed Uint8Array reference copying the received data.

- packages/shared/atlas/sagas.ts
Hotfix since POIs and Map information are not being reported to the renderer.
Reason: some ids here : https://github.com/decentraland/kernel/blob/main/packages/shared/atlas/sagas.ts#L188 are not OK (they have a `,` character) and it later fail fetching.
> hotfix: POIs and map info not being reported to renderer

- packages/shared/dao/sagas.ts
If `localStorage` saved ream is chosen instead, there is no way to optimize realm selection to gather people together, instead a normal distribution across realms was achieved in the long run.
> feat: prefer realm selection algorithm to get people together

- packages/shared/world/TeleportController.ts
Remove fetch to deprecated comms endpoint, use `/stats/parcels` instead
> Refactor to use /stats/parcels instead of /comms/status

- packages/entryPoints/index.ts
- packages/shared/atlas/actions.ts
- packages/shared/atlas/sagas.ts
- packages/shared/atlas/utils.ts
- packages/unity-interface/BrowserInterface.ts
- packages/unity-interface/IUnityInterface.ts
- packages/unity-interface/UnityInterface.ts
Closes #444 
Adds the required function to save and retrieve the home point coordinates,  also spawns the player in the home point position unless overwritten in the url with the "position" query parameter.
To be tested with the following unity-renderer branch:
> Feat: adds support to save and retrieve home point

- packages/shared/renderer/sagas.ts
- packages/shared/voiceChat/actions.ts
- packages/shared/voiceChat/handlers.ts
- packages/shared/voiceChat/sagas.ts
> pr feedback

- packages/shared/profiles/transformations/profileToRendererFormat.ts
- packages/shared/profiles/transformations/types.ts
Since the Renderer won't need this field anymore, this PR removes it from the `avatar` object. This is a follow-up PR to: https://github.com/decentraland/kernel/pull/486.
It was passed to the Renderer so it knows when to send emotes separately or not but since it will always send them as `emotes`, it's not needed.
> feat: Remove version field from the profile's avatar object

- packages/shared/chat/sagas.ts
- packages/unity-interface/IUnityInterface.ts
- packages/unity-interface/UnityInterface.ts
This PR adds a new chat command to send a message to Unity to detect which shapes are loaded as ABs and which as raw GLTFs. Command supports arguments to enable/disable shape coloring and to make the coloring local to current scene.
It is supposed to be tested together with Renderer PR:
https://github.com/decentraland/unity-renderer/pull/3099
Which closes this issue:
https://github.com/decentraland/unity-renderer/issues/2911
New chat commands are:
/detectabs => enable for all shapes
/detectabs off => disable for all shapes
/detectabs scene => enable for current scene shapes
/detectabs scene off => disable for current scene shapes (works only if "/decetabs scene" was used for this scene to enable) 
We need this debug tool in order to easily see if the shape was not converted to AB for some …
> feat: ab detection functionality

- packages/unity-interface/UnityInterface.ts
Unity is already ignoring rich text labels. Removing `<` `>` is not needed anymore.
- Now you can type <3 ❤️ .
- tags such as `<size=80>text</size>` should be ignored as rich text. Disclaimer: The input box is not ignoring them, that's something to be fixed in unity.
> chore: remove naive chat sanitization

- packages/shared/friends/sagas.ts
When a user creates a channel, it should not be included in the list of invites or the Matrix homeserver will complain
> fix: avoid sending user id to channel creation

- packages/shared/friends/sagas.ts
- test/unit/friends.saga.test.ts
> fix: lazy-loading fixes

- packages/shared/catalogs/sagas.ts
- packages/shared/catalogs/types.ts
Remove support for legacy emotes
All emotes were successfully migrated to the new emoteDataADR74 schema
> feat: Remove old emoteDataV0 in favor of emoteDataADR74

- package-lock.json
- package.json
Bump `dcl-social-client` version to 1.12.0 which includes an improvement on initial load, making use of a cache (IndexedDB)
The idea about this change is to persist Matrix sessions to avoid re-sync on every login.
> chore: bump `dcl-social-client` version to 1.12.0

- packages/shared/friends/sagas.ts
- test/unit/friends.saga.test.ts
This PR refactors some friends' tests to use the saga directly and react to actions instead of exporting a single function to be unit tested. 
Use redux-saga for tests
> refactor: change tests to use saga directly 

- packages/unity-interface/audioStream.ts
`AudioStream` playback was not being stopped when url contain spaces
fixes https://github.com/decentraland/sdk/issues/428
> fix: `AudioStream` not stopping in certain conditions

- static/preview.html
This PR fixes the issue where we get an error when trying to run the `preview.html` within a VSCode webview because it is detecting (correctly) that it is Electron, but the `window.electron` property does not exist in the context of a VSCode webview.
> fix: prevent ipcRenderer error when running kernel within VSCode webview

- package-lock.json
- package.json
- packages/shared/chat/sagas.ts
- packages/shared/friends/sagas.ts
- packages/shared/friends/utils.ts
- packages/shared/meta/types.ts
- packages/shared/profiles/sagas.ts
- packages/shared/profiles/transformations/profileToRendererFormat.ts
- packages/shared/types.ts
- test/unit/channels.saga.test.ts
1. Sends partial profiles to the explorer side when retrieving channel messages or members that are not in the catalog.
Partial profiles mean default avatars with a display name and image-related data to show in the chat window.
2. Prevent the creation of a channel in case a user who does not have permission (`users_allowed_to_create_channels`) to create it executes the /join command.
1. When opening a channel chat window or retrieving members, some of them are probably not in the catalog, and loading them there is very expensive and makes the experience to be bad.
> fix: send partial profiles to explorer to show up chat windows

- packages/shared/profiles/sagas.ts
- packages/shared/profiles/selectors.ts
- packages/shared/session/sagas.ts
Changes, If not guest: 
- Get the current profile always from the content server
- Enforce getting the latest version of the current profile from the server before making a deploy
> fix: Get latest profile before deploying

- packages/shared/dao/index.ts
Currently CATALYST=.. is not working if the catalyst is in the denylist
> fix: don't check denylist if the change is forced

- packages/shared/scene-loader/sagas.ts
Fix moveToParcel track event reporting 0,0 when you start
...
Kernel is reporting that we started on Genesis Plaza, and then we teleport out into the tile we actually had in the url, messing with our metrics
...
> fix track event moveToparcel

- package-lock.json
- package.json
- packages/shared/friends/sagas.ts
- packages/shared/friends/selectors.ts
- test/unit/channels.saga.test.ts
- test/unit/friends.saga.test.ts
Bump `dcl-social-client` to version `1.20.1` in oder to get DMs filtered by FriendshipStatus instead of room Membership
> fix: get DMs by FriendshipStatus instead of Membership

- package-lock.json
- package.json
- packages/shared/friends/sagas.ts
- packages/shared/friends/selectors.ts
We currently have concurrent update errors for different users when there are multiple rooms trying to set up `m.direct` on the initial sync.
So, to avoid the concurrent update error, we decided to set the user's `m.direct` events all at once with a single request, which allows us to lighten the number of updates and thus reduce the concurrent update error.
> feat: bump `dcl-social-client` to version `1.20.3`

- packages/shared/friends/sagas.ts
When the feature flag for presence is disabled, show the joined members of a channel instead of the online ones (as this information will not be available).
This is used as a mitigation tool to provide the best possible experience to the end user when the backend service cannot provide this feature.
> feat: return joined members when presence is disabled

- packages/unity-interface/nativeMessagesBridge.ts
Fixed native messages bridge `SetSceneNumber()` type sent
> fix: native messages bridge SetSceneNumber type

- packages/shared/friends/sagas.ts
Solves #689 
Probably solves #688 
Remove the listener where every member change is sent to Explorer.
In cases like joining a big channel is not well handled, sending N updates, where N is the number of members of that channel. 
The changes now are only sent when requested by Explorer.
> fix: do not send channel member update on every member

- package-lock.json
- package.json
- packages/entryPoints/inject.js
- packages/renderer-protocol/rpcClient.ts
- packages/renderer-protocol/transports/webSocketTransportAdapter.ts
- packages/renderer-protocol/transports/webTransport.ts
- packages/shared/apis/host/EngineAPI.ts
- packages/shared/apis/host/context.ts
- packages/shared/comms/adapters/OfflineAdapter.ts
- packages/shared/comms/adapters/SimulatorAdapter.ts
- packages/shared/comms/adapters/WebSocketAdapter.ts
- packages/shared/comms/adapters/voice/audioDebugger.ts
- packages/shared/index.ts
- packages/shared/realm/connections/BFFLegacy.ts
- packages/shared/renderer/actions.ts
- packages/shared/renderer/reducer.ts
- packages/shared/renderer/sagas.ts
- packages/shared/renderer/selectors.ts
- packages/shared/renderer/types.ts
- packages/shared/scene-loader/world-loader-impl/index.ts
- packages/shared/session/getPerformanceInfo.ts
- packages/shared/web3.ts
- packages/shared/world/SceneWorker.ts
- packages/shared/world/TeleportController.ts
- packages/shared/world/parcelSceneManager.ts
- packages/unity-interface/BrowserInterface.ts
- packages/unity-interface/initializer.ts
- packages/unity-interface/wsEditorAdapter.ts
- test/unit/RestrictedActions.test.tsx
Reverts decentraland/kernel#702
It seems like the released version of the renderer doesn't respond the binary messages over web sockets but the editor version does.
> Revert "fix: rpc race condition"

- packages/shared/friends/sagas.ts
Add the service that is being used for the chat to the log message
In order to know if the service that is failing
Closes #655
> feat: add the service used for the chat to error logs

- packages/shared/chat/sagas.ts
- packages/shared/dao/index.ts
- packages/shared/world/TeleportController.ts
- packages/unity-interface/BrowserInterface.ts
Adds features required in [#3547](https://app.zenhub.com/workspaces/explorer-6047bad476c3c0001942ee91/issues/decentraland/unity-renderer/3547)
Adds a realm check before any goTo command to go back to a DAO realms if necessary
Adds a `/world name` command to go directly to a world. No ENS required
Function `GoToMostPopulatedRealm()` was returning the least populated realm. Changed it back
> feat: Teleport worlds commands

- package-lock.json
- package.json
- packages/shared/apis/host/EnvironmentAPI.ts
- packages/unity-interface/BrowserInterface.ts
- packages/unity-interface/transformSerializationOpt.ts
Remove `useBinaryTrasnform`
No longer needed, breaks compatibility with very old renderers (+3 months)
> refactor: update scene-runtime and remove `useBinaryTransform`

- packages/renderer-protocol/inverseRpc/services/friendRequestService.ts
Unify error constructor function for any friendship service with the same error reply format.
...
> refactor: unify friendship error construction

- packages/shared/friends/sagas.ts
In case of success, if the friend request has a non-empty message body, it must be registered as part of the messages history of that user.
> feat: add message body to user's messages history

- packages/shared/friends/sagas.ts
- packages/shared/friends/utils.ts
- test/unit/friends.saga.test.ts
For the new flow of Friend Request, we've added a field called `friendRequestId`, which is generated by kernel when a request is created. This field is used to manage the actions that can be executed on a friendship. Since Matrix doesn't provide a way to generate a `friendshipId`, we've decided to generate one by using the addresses of the users involved, with the rule and pattern `addressUser1` < `addressUser2` ?  `addressUser1_addressUser2` : `addressUser2_addressUser1`.
But there's a problem with that, because (see the [video](https://github.com/decentraland/unity-renderer/pull/3823#pullrequestreview-1230652236) to understand better) in that way, from renderer they cannot differentiate between friend requests and subsequent actions and they end up having different information for the …
> fix: add request dispatcher to friendRequestId

- package-lock.json
- package.json
- packages/renderer-protocol/inverseRpc/rpcServer.ts
- packages/renderer-protocol/inverseRpc/services/friendsService.ts
- packages/shared/friends/sagas.ts
- packages/shared/friends/selectors.ts
- test/unit/friends.saga.test.ts
Following the definition outcome of this issue [decentraland/protocol#102](https://github.com/decentraland/protocol/issues/102), implement the service in kernel to retrieve the current friendship status of the current player for a given user id.
- Closes #825
> feat: add FriendsKernelService

- package-lock.json
- package.json
Remove `^` to prevent the kernel from using a higher version of `dcl-social-client`
> fix: set fixed version for `dcl-social-client`

- packages/shared/meta/selectors.ts
- packages/shared/meta/types.ts
- packages/unity-interface/kernelConfigForRenderer.ts
Fix https://github.com/decentraland/unity-renderer/issues/3880
Uses a feature flag to enable/disable the web gif processor. If it's disabled, it will use the unity gif processor.
> feat: add feature flag to enable the web gif processor instead of the unity gif processor

- packages/entryPoints/index.ts
- packages/shared/meta/selectors.ts
- packages/shared/meta/types.ts
Adding support for `new tutorial_variant` feature flag to A/B test the new flow
To support A/B test we need to be compatible with https://adr.decentraland.org/adr/ADR-73 and use variant to distinguish the cohort we are targeting.
> feat: A/B test support for new tutorial

- packages/entryPoints/index.ts
- packages/shared/profiles/selectors.ts
Added extra check for triggering new onboarding only for users not entering the platform via deeplink.
> fix: don't trigger new onboarding for users entering via deeplink
