decentraland/kernel

kernel/static/index.html
kernel/static/preview.html

Change observable handlers in index.html and preview.html to a global observable.
In accordance with https://github.com/decentraland/kernel/commit/9627357fc4f870db4dd378d72fc02a5b8f37e306, preview.html and index.html need to use this modified way to handle events from kernel.

fix: change each observable handler object to global observable

---

packages/unity-interface/trace.ts

chore: add endTrace

---

Makefile
package.json
packages/entryPoints/index.ts
packages/shared/loading/sagas.ts
packages/shared/meta/sagas.ts

Track scene load failures with used catalyst information

chore: track failed scene loads

---

packages/shared/renderer/sagas.ts
packages/unity-interface/initializer.ts

chore: loading improvements

---

.github/workflows/test-build-deploy.yml

chore: add s3 npm install notify to test

---

packages/shared/apis/SceneStateStorageController/BuilderServerAPIManager.ts
packages/shared/apis/SceneStateStorageController/StorableSceneStateTranslation.ts
packages/shared/apis/SceneStateStorageController/utils.ts

Fixes decentraland/unity-renderer#950
This PR set the correct name for builder so when it publish the scene , it does it correctly

fix: biw correct name set in builder format

---

packages/shared/session/sagas.ts
static/preview.html

In preview mode, skip show avatar selection.
https://github.com/decentraland/sdk/issues/46

feat: skip the avatar selection in preview and export

---

packages/unity-interface/BrowserInterface.ts

Add DEBUG condition to show unknown unity message.
...

feat: show unknown unity message only in debug mode

---

packages/unity-interface/BrowserInterface.ts

Add video event handler and it's emitted to the owner scene.
https://github.com/decentraland/sdk/issues/11

feat: add video event handler and it's emitted to the owner scene

---

packages/unity-interface/BrowserInterface.ts

Change the video event parameters. 
Copy from https://github.com/decentraland/unity-renderer/pull/1012/files#diff-28362e781c84c604519dfdc08206519a09a0f34e8eab4872d76b4bb896db1527R1292
They're wrong copied

fix: change video event report parameters

---

packages/unity-interface/BrowserInterface.ts

fix: videoTextureId instead of videoClipId

---

packages/entryPoints/index.ts
packages/shared/meta/sagas.ts
packages/shared/meta/selectors.ts
packages/shared/meta/types.ts
packages/shared/types.ts
packages/unity-interface/IUnityInterface.ts
packages/unity-interface/UnityInterface.ts
packages/unity-interface/kernelConfigForRenderer.ts

This PR makes the flag system to be automatic so we don't need to add a PR to kernel each time a flag is added
We wanted to eliminate the need of a PR in kernel each time a flag is added

refactor: automatic flag system

---

packages/shared/profiles/ProfileAsPromise.ts
packages/shared/profiles/actions.ts
packages/shared/profiles/sagas.ts

So we can use cache. This closes issue #63

chore: Requesting profiles using version

---

packages/entryPoints/index.ts

issue: https://github.com/decentraland/sdk/issues/89

fix: disable asset bundles in preview

---

packages/shared/profiles/sagas.ts

fix: unhandled error

---

packages/unity-interface/BrowserInterface.ts

As mentioned in this [issue](https://github.com/decentraland/unity-renderer/issues/1248), the friend request fails when you try to send a friend request typing a user name (ie: `somenickname#d54g`) in friends panel.
The changes now searches for a user with the given name when cannot find it in the first place.
You should be able to send the friend request just by typing the user's name.

fix: add friend from user name

---

packages/unity-interface/dcl.ts

Don't merge until https://github.com/decentraland/posix/pull/4 and https://github.com/decentraland/js-sdk-toolchain/pull/42 are merged.
https://github.com/decentraland/sdk/issues/113

feat: add allSceneEvent the pointer lock event

---

packages/shared/catalogs/sagas.ts

feat: add catalog source for wearable in preview mode

---

packages/entryPoints/index.ts
packages/shared/wearablesPortableExperience/sagas.ts
packages/unity-interface/dcl.ts

temp: add hotreloading for portable experiences
...
...

feat: add hotreloading for portable experiences

---

packages/shared/apis/EnvironmentAPI.ts
packages/shared/comms/sagas.ts

send `onRealmChanged` to all scenes when realm and/or island is set

feat: add realm changed event for sdk

---

package-lock.json
package.json
packages/entryPoints/index.ts
packages/unity-interface/dcl.ts

add ws types

---

packages/shared/apis/Players.ts
packages/shared/social/avatarTracker.ts
packages/shared/types.ts
packages/unity-interface/BrowserInterface.ts

+report player enter/leave scene
+add `getPlayersInScene` to fetch players currently inside scene

feat: add enter and leave scene events for remote user

---

.github/dependabot.yml

add dependabot for dcl packages

---

packages/shared/apis/Players.ts
packages/shared/comms/sagas.ts
packages/shared/profiles/sagas.ts
packages/shared/sceneEvents/sagas.ts
packages/shared/sceneEvents/visibleAvatars.ts
packages/shared/social/avatarTracker.ts
packages/shared/store/rootSaga.ts
test/index.ts
test/shared/sceneEvents/index.ts
test/shared/sceneEvents/sagas.spec.ts
test/shared/sceneEvents/visibleAvatars.spec.ts

Closes https://github.com/decentraland/sdk/issues/141
Move allSceneEvents to a new saga folder.
...
To avoid having allSceneEvents sagas handler all over kernel. 
Add tests for scene events saga.
...

refactor allscene events.

---

packages/shared/apis/expressionExplainer.ts

Closes https://github.com/decentraland/kernel/pull/138
...
...

add xmas emotes

---

.github/workflows/update-unity-renderer.yml

add unity-renderer cron job to verify the latest version installed

---

packages/shared/dao/index.ts

Reverts decentraland/kernel#162

Revert "Add filter to prevent selecting a catalyst without capacity"

---

packages/decentraland-loader/lifecycle/controllers/parcel.ts
packages/shared/catalogs/sagas.ts
packages/unity-interface/wsEditorAdapter.ts

Fixes a problem by deleting it
...

fix: problem with catalyst helper function

---

Makefile
packages/shared/apis/Permissions.ts

chore: set regular empty scenes and remove default permission of websocket and fetch in px

---

package-lock.json
package.json
packages/shared/catalogs/types.ts
packages/shared/types.ts
packages/shared/wearablesPortableExperience/sagas.ts
packages/unity-interface/portableExperiencesUtils.ts

closes https://github.com/decentraland/sdk/issues/161

fix: use content mapping instead of url for smart wearables icon

---

packages/entryPoints/index.ts
packages/unity-interface/dcl.ts

https://github.com/decentraland/cli/pull/622
https://github.com/decentraland/js-sdk-toolchain/pull/89

feat: enable to hot-reload multiple projects in the same preview (workspaces)

---

packages/shared/catalogs/sagas.ts

fix: filter the owned wearables with problem and show the error in the defaultLogger

---

packages/ui/decentraland-ui.scene.ts

trigger build

---

packages/entryPoints/index.ts

can be merged after this PR: https://github.com/decentraland/unity-renderer/pull/1845

feat: add preview mode menu

---

packages/shared/catalogs/sagas.ts

chore: add tracking to fetch wearable event when it fails

---

packages/decentraland-loader/lifecycle/controllers/position.ts
packages/shared/analytics/hook-observable.ts
packages/shared/analytics/index.ts
packages/shared/analytics/types.ts
packages/shared/world/parcelSceneManager.ts
packages/unity-interface/BrowserInterface.ts

add analytics types

---

packages/shared/profiles/sagas.ts

fix face256 undefined on preview

---

packages/shared/comms/index.ts
packages/shared/comms/types.ts

feat: remove peer-parameters

---

.github/workflows/set-rollouts.yml

chore: change to 0 percentage of .org rollout

---

.github/workflows/set-rollouts.yml

Reverts decentraland/kernel#218

Revert "chore: change to 0 percentage of .org rollout"

---

static/preview.html

feat: add kernel-branch query param to debug between versions (preview mode)

---

packages/shared/catalogs/sagas.ts
packages/shared/catalogs/types.ts

Added `EmoteV2Data` property to the `WearableV2` type.

feat: added EmoteDataV0 to WearableV2

---

packages/shared/comms/index.ts

feat: enable "simple comms" over WebSockets

---

packages/shared/analytics/hook-observable.ts
packages/shared/analytics/types.ts
packages/shared/chat/sagas.ts
packages/shared/comms/interface/types.ts
packages/shared/friends/sagas.ts

Added tracking to friendship updates events.
Added MessageType to chat events.

feat: add tracking to friends events

---

packages/config/index.ts
packages/shared/logger/index.ts
packages/unity-interface/BrowserInterface.ts
packages/unity-interface/IUnityInterface.ts
packages/unity-interface/UnityInterface.ts

Fix: decentraland/explorer-desktop#173

feat: add report log from unity

---

static/preview.html

chore: change ipcRenderer getting in preview mode for desktop preview

---

packages/ui/avatar/avatarSystem.ts

fix: unique entity ids avatars

---

packages/shared/dao/index.ts
packages/shared/dao/sagas.ts

hotfix: also hit lambdas to check liveness

---

package-lock.json
package.json
packages/config/index.ts
packages/entryPoints/index.ts
packages/shared/apis/EnvironmentAPI.ts
packages/shared/comms/v1/brokerWorldInstanceConnection.ts
packages/shared/dao/sagas.ts
packages/shared/friends/sagas.ts
packages/shared/meta/reducer.ts
packages/shared/meta/sagas.ts
packages/shared/meta/selectors.ts
packages/shared/meta/types.ts
packages/shared/quests/sagas.ts
packages/shared/world/parcelSceneManager.ts

chore: some hotfixes

---

packages/shared/comms/peers.ts
packages/shared/comms/sagas.ts
packages/shared/meta/sagas.ts
packages/shared/meta/selectors.ts
packages/shared/meta/types.ts

fix: max avatars

---

packages/shared/chat/sagas.ts
packages/shared/rolloutVersions.ts
packages/shared/session/getPerformanceInfo.ts
packages/unity-interface/BrowserInterface.ts
packages/unity-interface/nativeMessagesBridge.ts
packages/unity-interface/trace.ts
test/unit/getPerformanceInfo.test.tsx

chore: fix renderer message counter

---

packages/shared/session/getPerformanceInfo.ts
packages/unity-interface/BrowserInterface.ts
test/unit/getPerformanceInfo.test.tsx

chore: add more metrics

---

package-lock.json
package.json
packages/shared/meta/sagas.ts
packages/shared/meta/types.ts
packages/shared/portableExperiences/actions.ts
packages/shared/portableExperiences/reducer.ts
packages/shared/portableExperiences/sagas.ts
packages/shared/portableExperiences/selectors.ts
packages/shared/portableExperiences/types.ts
packages/unity-interface/portableExperiencesUtils.ts
test/unit/portable-experiences.test.tsx

enable portable experiences with CI using feature flag variants

---

package-lock.json
package.json
packages/shared/friends/sagas.ts
packages/shared/meta/types.ts

It updates the `matrix-client` version with constructor options and sets feature flag for disable presence.

feat: add disable presence feature flag for matrix client

---

package-lock.json
package.json

This bump includes an important fix to avoid multiple calls (repeated) that fail because of the lack of concurrency support.

chore: bump `dcl-social-client` version

---

packages/shared/friends/sagas.ts

Removes the chat notification being sent to the chat window every time a friend status is received to avoid flooding the chat window.
...

fix: remove chat status notification

---

packages/shared/apis/host/EngineAPI.ts

fix: wrong payload getter of openExternalUrl

---

packages/shared/apis/host/SocialController.ts
packages/shared/apis/proto/SocialController.proto
packages/ui/decentraland-ui.scene.ts

fix: slow changerealm with avatar batch events

---

packages/shared/apis/host/EthereumController.ts

fix: type context controller and fix the sceneId params.

---

package-lock.json
package.json
packages/shared/friends/sagas.ts
packages/shared/friends/types.ts
packages/shared/types.ts
packages/unity-interface/BrowserInterface.ts
packages/unity-interface/IUnityInterface.ts
packages/unity-interface/UnityInterface.ts
test/unit/RestrictedActions.test.tsx
test/unit/friends.saga.test.ts

Closes #343 
Add friend requests lazy loading

Feat: add requests lazy loading

---

package-lock.json
package.json
packages/shared/friends/sagas.ts
packages/shared/friends/selectors.ts
packages/shared/profiles/selectors.ts
packages/shared/types.ts
packages/unity-interface/BrowserInterface.ts
packages/unity-interface/IUnityInterface.ts
packages/unity-interface/UnityInterface.ts
test/unit/friends.saga.test.ts

Add lazy loading of all existent conversations
Closes #345

Add conversations list

---

packages/shared/dao/index.ts
packages/shared/dao/sagas.ts
packages/shared/meta/selectors.ts
packages/shared/meta/types.ts
test/dao/fetchCatalystStatuses.test.ts

Added new feature flag to list catalyst to be removed from the options in pick realm algorithm.

Add support for feature flag to disable some catalysts

---

packages/shared/wearablesPortableExperience/sagas.ts

fix: (smart wearable) find scene json and set default 

---

packages/shared/analytics/types.ts
packages/shared/occurences.ts
packages/shared/session/getPerformanceInfo.ts
packages/shared/world/SceneWorker.ts
packages/unity-interface/UnityInterface.ts

chore: simplify metrics counters

---

package-lock.json
package.json
packages/shared/friends/sagas.ts
packages/shared/types.ts
packages/unity-interface/BrowserInterface.ts
packages/unity-interface/IUnityInterface.ts
packages/unity-interface/UnityInterface.ts
test/unit/friends.saga.test.ts

Closes https://github.com/decentraland/kernel/issues/345
Add lazy loading of private conversation

Feat: get private chat messages

---

packages/shared/friends/sagas.ts
packages/shared/friends/selectors.ts
packages/shared/friends/utils.ts
packages/shared/types.ts
packages/unity-interface/IUnityInterface.ts
packages/unity-interface/UnityInterface.ts
test/unit/friends.saga.test.ts

Lazy loading integration with unity fixes

---

packages/shared/dao/reducer.ts

Fix: add v3 as valid protocol for lighthouse

---

packages/shared/apis/host/ParcelIdentity.ts
packages/unity-interface/BrowserInterface.ts
packages/unity-interface/wsEditorAdapter.ts
packages/voice-chat-codec/VoiceCommunicator.ts

remove linter warnings

---

packages/shared/dao/index.ts

fix: add usersCount for loadBalancing

---

packages/config/index.ts
packages/shared/comms/v3/InstanceConnection.ts

fix: only log comms in DEBUG_MODE

---

packages/shared/comms/v3/InstanceConnection.ts

fix: typo; logging as comms v4 instead of v3

---

packages/shared/comms/actions.ts
packages/shared/comms/reducer.ts
packages/shared/comms/selectors.ts
packages/shared/comms/types.ts
packages/shared/comms/voice-over-comms.ts
packages/shared/comms/voice-sagas.ts
packages/unity-interface/BrowserInterface.ts
packages/unity-interface/IUnityInterface.ts
packages/unity-interface/UnityInterface.ts

Test url:
https://play.decentraland.org/?kernel-branch=feat/join-leave-voice-chat&renderer-branch=feat/implement-manual-connection-to-voice-chat

feat: join/leave voice chat

---

packages/scene-system/sdk/runtime/DecentralandInterface.ts

fix regression

---

package-lock.json
package.json
packages/shared/apis/host/UserIdentity.ts
packages/shared/friends/ensureFriendProfile.ts
packages/shared/friends/sagas.ts
packages/shared/profiles/ProfileAsPromise.ts
packages/shared/profiles/sagas.ts
packages/shared/profiles/selectors.ts
packages/shared/profiles/transformations/profileToRendererFormat.ts
packages/unity-interface/BrowserInterface.ts
test/unit/friends.saga.test.ts

fix: unread message count

---

packages/shared/profiles/ProfileAsPromise.ts
packages/shared/profiles/sagas.ts
test/unit/profiles.saga.test.tsx

Fix:  generate default avatars for invalid/inexistent users

---

packages/shared/analytics/types.ts
packages/shared/profiles/sagas.ts
packages/shared/profiles/transformations/profileToServerFormat.ts
packages/unity-interface/BrowserInterface.ts

This PR enables compatibility with normalized types in new versions of unity renderer
...

fix: add compatibility layer

---

packages/unity-interface/BrowserInterface.ts

remove version field

---

package-lock.json
package.json

re-use same livekit from comms3-transports

---

packages/ui/avatar/avatarSystem.ts

Hack until this is merged and implemented in renderer https://github.com/decentraland/protocol/pull/39 
...

fix: emotes

---

package-lock.json
package.json
packages/shared/apis/host/ExperimentalAPI.ts

chore: update @dcl/protocol

---

packages/shared/comms/v3/BFFConnection.ts
packages/shared/comms/v3/InstanceConnection.ts

- Try to avoid bff messages after disconnection
- Full authentication for the BFF even if address is already connected

Chore: comms improvements

---

packages/shared/catalogs/sagas.ts

Force downloading a thumbnail when using the explorer in debug mode
Sometimes chrome gives CORS error downloading files from S3 due to cache
behavior

fix: Thumbnail loading CORS error

---

packages/shared/friends/sagas.ts

Send an update with unseen messages to Renderer when the client receives a new message from a channel.
Closes #326

feat: send unread messages update on channel messages

---

packages/shared/friends/sagas.ts
packages/shared/friends/utils.ts
packages/shared/meta/types.ts
packages/unity-interface/BrowserInterface.ts

Closes #551
Add feature flag to disable matrix channels communication with renderer

feat: add matrix channels feature flag

---

packages/unity-interface/dcl.ts

Enable the feature of content mapping in the `sdk-playground` => https://github.com/decentraland/sdk-playground/pull/10

feat: add content mapping to playground

---

package-lock.json
package.json

Bump the version of matrix-client pkg
Introduce a fix

feat: bump matrix-client version

---

packages/unity-interface/UnityInterface.ts

implement ADR-32

---

packages/shared/friends/sagas.ts
packages/shared/profiles/sagas.ts
packages/shared/profiles/transformations/profileToRendererFormat.ts
packages/shared/types.ts

refactor: build profile image url without snapshots

---

package-lock.json
package.json
packages/shared/chat/actions.ts
packages/shared/chat/sagas.ts
packages/shared/friends/actions.ts
packages/shared/friends/sagas.ts

Bump to `matrix-client` to version `1.19.2 `
Wait for `message id` before sending any confirmation to the renderer

fix: handle new messages differently

---

packages/shared/world/SceneWorker.ts

Fix granted permissions when the scene is loaded.
...

fix: typo - add PI_ sufix to permission convertion

---

packages/config/index.ts
packages/shared/types.ts
packages/unity-interface/kernelConfigForRenderer.ts

added avatarTextureAPIBaseUrl value sent through KernelConfig to the renderer

chore: send avatar texture API base URL to renderer

---

package-lock.json
package.json
packages/shared/chat/actions.ts
packages/shared/chat/sagas.ts
packages/shared/friends/actions.ts
packages/shared/friends/sagas.ts
packages/shared/friends/utils.ts
packages/shared/types.ts
test/unit/channels.saga.test.ts

Bump to `matrix-client` to version `1.18.0 `
Listen for channel members updates and notify the updates to explorer
Send joined members count on channel leave action
Send online members count on get joined channels action

fix: update channel info when members change

---

package-lock.json
package.json
packages/shared/scene-loader/sagas.ts

See static/preview.html, the base-url is `/@/artifacts`.
https://github.com/decentraland/scene-runtime/pull/20 is necessary to also fix ecs7.

fix: empty parcels in preview mode

---

packages/shared/comms/adapters/SimulatorAdapter.ts
packages/shared/comms/handlers.ts
packages/shared/comms/interface/types.ts
packages/shared/comms/peers.ts
packages/shared/profiles/ProfileAsPromise.ts
packages/shared/profiles/actions.ts
packages/shared/profiles/reducer.ts
packages/shared/profiles/sagas.ts
packages/shared/profiles/selectors.ts
packages/shared/session/sagas.ts
packages/shared/wearablesPortableExperience/sagas.ts
test/unit/profiles.saga.test.tsx

refactor: profile as promise

---

packages/shared/chat/sagas.ts
packages/shared/world/TeleportController.ts

Implements /goto home chat command
...

feat: teleport home command

---

packages/shared/analytics/types.ts
packages/shared/profiles/sagas.ts
packages/shared/renderer/sagas.ts
packages/unity-interface/fetchENSOwnerProfile.ts

Closes https://github.com/decentraland/unity-renderer/issues/3379

Fix Desyncronization when loading profile from localstorage

---

packages/config/index.ts
packages/shared/meta/sagas.ts
packages/shared/meta/selectors.ts
packages/shared/meta/types.ts

This PR adds the social server feature, it also adds a feature flag to roll out of the usage of synapse. This PR also allows for usage of a different social server
Closes #650 
...
...

Feat: Add social service url and feature flag

---

packages/shared/analytics/types.ts
packages/shared/meta/selectors.ts
test/index.ts
test/unit/meta.test.tsx

add validation for denied catalyst urls

---

packages/shared/web3.ts

fix: make queryGraph calls to be POST

---

package-lock.json
package.json
packages/entryPoints/inject.js
packages/renderer-protocol/rpcClient.ts
packages/renderer-protocol/transports/webSocketTransportAdapter.ts
packages/renderer-protocol/transports/webTransport.ts
packages/shared/apis/host/EngineAPI.ts
packages/shared/apis/host/context.ts
packages/shared/comms/adapters/OfflineAdapter.ts
packages/shared/comms/adapters/SimulatorAdapter.ts
packages/shared/comms/adapters/WebSocketAdapter.ts
packages/shared/comms/adapters/voice/audioDebugger.ts
packages/shared/index.ts
packages/shared/realm/connections/BFFLegacy.ts
packages/shared/renderer/actions.ts
packages/shared/renderer/reducer.ts
packages/shared/renderer/sagas.ts
packages/shared/renderer/selectors.ts
packages/shared/renderer/types.ts
packages/shared/scene-loader/world-loader-impl/index.ts
packages/shared/session/getPerformanceInfo.ts
packages/shared/web3.ts
packages/shared/world/SceneWorker.ts
packages/shared/world/TeleportController.ts
packages/shared/world/parcelSceneManager.ts
packages/unity-interface/BrowserInterface.ts
packages/unity-interface/initializer.ts
packages/unity-interface/wsEditorAdapter.ts
static/package.json
test/unit/RestrictedActions.test.tsx

This reverts commit 06ff9555f4fbc20db890ed4875f346ee4ed8a8e4.

feat: increment major version and revert "Revert "fix: rpc race condition (#702)" (#712)"

---

packages/shared/profiles/sagas.ts

Fix https://github.com/decentraland/unity-renderer/issues/3527

fix: peer profile changes

---

packages/renderer-protocol/transports/webTransport.ts

fix: prevent unhandled errors in main thread

---

packages/shared/comms/sagas.ts
packages/shared/session/getPerformanceInfo.ts

Add comms protocol tag in metrics for ping

feat: Add protocol in PerformanceInfo

---

packages/shared/apis/host/EngineAPI.ts

chore: add crdtSendToRenderer comment

---

packages/unity-interface/dcl.ts

This reverts commit 4997e87dcea5c2bfa48b2015c5c61df939c3808e.

Revert "fix: add ecs7 option to global scenes"

---

packages/shared/apis/host/EngineAPI.ts
packages/shared/apis/host/context.ts
packages/shared/types.ts
packages/shared/world/SceneWorker.ts
packages/unity-interface/BrowserInterface.ts
packages/unity-interface/IUnityInterface.ts
packages/unity-interface/UnityInterface.ts
packages/unity-interface/transformSerializationOpt.ts
test/unit/RestrictedActions.test.tsx

Related to https://github.com/decentraland/protocol/pull/83
Related to https://github.com/decentraland/sdk/issues/474

feat: ecs7 to renderer

---

packages/unity-interface/dcl.ts

Add `ecs7` to the scene metadata in Playground scene.

fix: playground set ecs7 scene

---

package-lock.json
package.json
packages/shared/dao/index.ts
test/sceneEvents/comms.spec.ts
test/unit/comms-resolver.test.tsx

fix: add missing `acceptingUsers: true` to the tests and offline request /about

chore: update @dcl/protocol and fix kernel error on build

---

package-lock.json
package.json

Enables debug sourcemaps in SDK7 scenes & better sandboxing

chore: update scene runtime

---

packages/shared/analytics/types.ts
packages/shared/comms/adapters/LivekitAdapter.ts
packages/shared/comms/sagas.ts
packages/shared/wearablesPortableExperience/sagas.ts
packages/unity-interface/BrowserInterface.ts

prevent failing with big messages

---

Dockerfile
docker-compose.yml
init.sh

- upgraded to docker-compose version 3
- copy init.sh into the container and apply executable permissions
- add shebang to specify bash interpreter and show errors

Fix docker compose

---

packages/shared/friends/sagas.ts

This branch continues the work for the New Friend Request feature. Find more info about the proposal [here](https://www.notion.so/decentraland/PRD-New-Friend-Requests-188555225272448f91f3eea5e84f1cd3) and check the RFC [here](https://adr.decentraland.org/adr/ADR-137). **The messages exchange between kernel and renderer is defined by RPC calls.**
So far, the PR addresses:
- Cancel friend request (Push notifications)
- Reject friend request (Push notifications)
- Approve friend request (Push notifications)

feat: friend request push notifications

---

packages/renderer-protocol/inverseRpc/services/friendRequestService.ts

Abstracts the flow of request handling of friend requests.
...

refactor: generic request handling

---

packages/shared/loadingScreen/sagas.ts

Signed-off-by: Esteban Ordano <esteban@decentraland.org>
...
...

fix: sceneLoader.positionSettled does not exist anymore

---

package-lock.json
package.json
packages/entryPoints/index.ts
packages/renderer-protocol/inverseRpc/services/friendRequestService.ts
packages/shared/analytics/types.ts
packages/shared/loadingScreen/sagas.ts
packages/shared/meta/types.ts
packages/shared/world/SceneWorker.ts
packages/unity-interface/IUnityInterface.ts
packages/unity-interface/UnityInterface.ts

Add the ?RESET_TUTORIAL=&ENABLE_NEW_TUTORIAL= to the URL to test it. It should take you to menduz.dcl.eth or the realm configured in the feature flag named `explorer-new_tutorial`

New onboarding feature flag

---

packages/entryPoints/index.ts

fix: remove blocking condition for tutorial

---

packages/entryPoints/index.ts

Fix https://github.com/decentraland/unity-renderer/issues/3932

feat: change default spawn point genesis plaza, christmas is over

---

packages/shared/profiles/sagas.ts

fix: users being sent to avatar creation scene

---

packages/shared/friends/sagas.ts
test/unit/friends.saga.test.ts

Prevent the user to send a friend request to themself.

feat: validate if the user tries to send a request to themself

---

packages/shared/world/SceneWorker.ts

Signed-off-by: Juan Ignacio Molteni <juanignaciomolteni@gmail.com>
...
...

chore: update scene load timeout to 90

---

packages/entryPoints/index.ts

The new tutorial was not starting in org
The flag was missing a undefined check

fix: tutorial not starting in org

---

packages/shared/renderer/sagas.ts
test/unit/profiles.saga.test.tsx

fix: check profile status tests

---

packages/shared/loadingScreen/sagas.ts

Signed-off-by: Esteban Ordano <esteban@decentraland.org>
...
...

fix: flicker on loading

---

packages/unity-interface/UnityInterface.ts

Not sure why, but this is nuts for perf

fix: don't scope all calls to unity

---

.devcontainer/devcontainer.json
packages/shared/dao/selectors.ts
packages/shared/meta/types.ts

Enables legacy comms via feature flag

feature flag to enable legacy comms

---

packages/shared/comms/sagas.ts

throttle profile announcement messages
